apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ad-web
  labels:
    app: ad-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-web
  template:
    metadata:
      labels:
        app: ad-web
    spec:
      containers:
      - name: ad-web
        image: 10.10.50.4/dfws/ad-web:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
---
kind: Service
apiVersion: v1
metadata:
  name: ad-web
  labels:
    app: ad-web
spec:
  selector:
    app: ad-web
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ad-web
  annotations:
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ad.admin.dfwsgroup.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ad-web
          servicePort: 80
